### PR TITLE
Offset total count connections

### PR DESCRIPTION
**Pull request by doug-martin**
## Offset Paging Strategy [BREAKING CHANGE]

In previous versions of `nestjs-query` the `OFFSET` paging strategy returned an array of nodes, this proved to not be
extensible, especially when wanting to expose other attributes such as `totalCount`, or paging meta such has
`hasNextPage` or `hasPreviousPage`.

In `v0.23.0` the graphql response now returns an `OffsetConnection` that looks like the following

```graphql
type OffsetPageInfo {
  hasNextPage: Boolean
  hasPreviousPage: Boolean
}

type TodoItemConnection {
  pageInfo: OffsetPageInfo!
  nodes: [TodoItem!]!
}

type TodoItem {
  id: ID!
  title: String!
  description: String
  completed: Boolean!
  created: DateTime!
  updated: DateTime!
}
```

## Total Count with OFFSET Strategy

In previous versions of the nestjs-query the `enableTotalCount` option only worked with the `CURSOR` paging strategy.
 In `v0.23.0` the `enableTotalCount` option now also works with the `OFFSET` paging strategy.

 When `enableTotalCount` is set to true the following graphql schema will be generated

```graphql
type OffsetPageInfo {
  hasNextPage: Boolean
  hasPreviousPage: Boolean
}

type TodoItemConnection {
  totalCount: Int!
  pageInfo: OffsetPageInfo!
  nodes: [TodoItem!]!
}

type TodoItem {
  id: ID!
  title: String!
  description: String
  completed: Boolean!
  created: DateTime!
  updated: DateTime!
}
```

## Relation Decorator Changes [BREAKING CHANGE]

In previous versions of `nestjs-query` there were four relation decorators `@Relation`, `@FilterableRelation`,
`@Connection`, and `@FilterableConnection` all four of the decorators have been changed to be more explicit in naming
 to be clear in what they are doing.

In `v0.23.0` the decorators have been renamed to be more explicit.

* `@Relation` - A relation that is a single value (one-to-one, many-to-one)
* `@FilterableRelation` - A `@Relation` that enables filtering the parent by fields of the relation `DTO`.
* `@UnPagedRelation` - An array of relations (e.g, many-to-many, one-to-many) that returns all the related records.
* `@FilterableUnPagedRelation` - An `@UnPagedRelation` that enables filtering the parent by fields of the relation
`DTO`.
* `@OffsetConnection` - A connection that represents a collection (e.g, many-to-many, one-to-many) that uses `offset`
 based pagination.
* `@FilterableOffsetConnection` - An `@OffsetConnection` that enables filtering the parent by fields of the connection
 `DTO`.
* `@CursorConnection` - A connection that represents a collection (e.g, many-to-many, one-to-many) that uses `cursor`
 based pagination.
* `@FilterableCursorConnection` - A `@CursorConnection` that enables filtering the parent by fields of the
 connection `DTO`.

Below is a mapping of the old definition to the new one

**warning** In previous versions the `OFFSET` paging strategy returned an array of relations, the new version returns an
`OffsetConnection`

```ts
//old
@Relation('subTasks', () => [TodoItem])
//new
@OffsetConnection('subTasks', () => TodoItem)
```

```ts
//old
@FilterableRelation('subTasks', () => [TodoItem])
//new
@FilterableOffsetConnection('subTasks', () => TodoItem)
```

```ts
//old
@Relation('subTasks', () => [TodoItem], {pagingStrategy: PagingStrategies.NONE})
//new
@UnPagedRelations('subTasks', () => TodoItem)
```

```ts
//old
@FilterableRelation('subTasks', () => [TodoItem], {pagingStrategy: PagingStrategies.NONE})
//new
@FilterableUnPagedRelations('subTasks', () => TodoItem)
```

```ts
//old
@Connection('subTasks', () => TodoItem)
//new
@CursorConnection('subTasks', () => TodoItem)
```

```ts
//old
@FilterableConnection('subTasks', () => TodoItem)
//new
@FilterableCursorConnection('subTasks', () => TodoItem)
```

### CODE REVIEW

**Comment by doug-martin** [comment]
@thehappycoder @incode4it @smolinari this PR should address the enableTotalCount issue #790 

In order to support this I needed to change some things, you can read about it above. The larger breaking change (other than returning an array) is making the decorators more explicit, this change also has the side benefit of breaking any apps that may have relied on the old version to ensure they update.

Let me know what you think all suggestions are welcome!

**Comment by thehappycoder** [comment]
@doug-martin I like the new changes, especially the main one that with offset pagination strategy, the shape now included information about pagination. With the old shape, it is very confusing and it actually caused a bug in my application since I assumed I got all records from my relation.

Just want to share that in my project, my output types often have relations with both PagingStrategies.NONE and PagingStrategies.CURSOR strategy and to know the difference between the two, I prefix of one the fields with `all`. May be a good naming convention for the documentation.

**Comment by doug-martin** [comment]
@thehappycoder I've had a really hard time figuring out what to name that decorator, I think I like the direction your going. 

To make sure we're on the same page, I was thinking `@AllRelations` and `@FilterableAllRelations` instead of the unpaged version.

**Comment by doug-martin** [comment]
@thehappycoder I went ahead and made the change thank you for the suggestion!

**Comment by thehappycoder** [comment]
@doug-martin I actually prefix the fields with `all` only. For decorators, not sure I like `@AllRelations and @FilterableAllRelations` even though they are shorter. I like the old names more.

**Comment by smolinari** [comment]
LGTM! 👍 

Scott

**Pull request merged**
