### PR TITLE
feat(typegoose): Add typegoose package

### PR DESCRIPTION
**Pull request by doug-martin**

### CODE REVIEW

**Comment by JohnMcInall** [comment]
@doug-martin I noticed that a commit I made ([1fda249](https://github.com/doug-martin/nestjs-query/pull/846/commits/1fda2498b157d039f097c3dc1d7091e4980f57f8)) relies on a specific implementation outwith this package to work, I can show you if you would like to see if it is something you may want to add. This just gives the ability to add single items to array instead of inserting the full array every time. I had to make some custom types to support this which I have in another project that could possibly be added to this or the core package to support this functionality.

**Comment by smolinari** [comment]
@doug-martin @JohnMcInall - Typegoose is about to come out with version 8, where it will be supporting the newer versions of Mongoose and their new types. I've been asked to test it and I'd like to add it to query-typegoose as one of the "tests". 

Is that ok with you both? What would your suggestions be to make this happen? Close this PR and start a new one? Or just commit the changes with the new version?

Scott

**Comment by doug-martin** [comment]
@smolinari I'm ok with that, as this PR stands its going to be really hard to get it merged because we have diverged mongoose versions. If you want to work against this branch and test it out go for It and we can just merge that one when its ready.

**Comment by smolinari** [comment]
@doug-martin - Just a quick update. Got things going with the upcoming Typegoose 8.0 with the newest Mongoose version. :) Now moving to e2e tests. 

image

Scott

**Comment by smolinari** [comment]
And, now e2e tests are passing. :)

image

I had to revert `class-transformer` back to version `0.3.1` as `0.3.2` caused very ugly warning from Nest. 

image


Scott

**Pull request merged**
