### PR TITLE
feat(mongodb): Add support for MongoDB

### PR DESCRIPTION
**Pull request by marian2js**
This PR adds the package `query-typegoose` which adds support for Typegoose.

### Changes done:

- [x] CRUD operations
- [x] Query filters
- [x] Query pagination
- [x] Query sorting
- [x] References
- [ ] Example with e2e
- [ ] Documentation
- [ ] Clean up all references to typeorm
- [ ] Make query service return entity instances
- [x] Support new authentication filter

### Features not implemented
- nestjs-query aggregations

Currently nestjs-query does not support MongoDB, since the package query-typeorm makes use of QueryBuilder which is not supported by the MongoDB driver.
TypeORM support for MongoDB is very limited, so this PR uses [nestjs-typegoose](https://github.com/kpfromer/nestjs-typegoose) instead.

This is an example of an entity using `@nestjs-query/query-typegoose`

```ts
@Relation('owner', () => User)
export class TodoItem {
  // Mongoose virtual property to map _id to id on the GraphQL schema
  @FilterableField(() => ID)
  get id () {
    return (this as any)._id?.toString()
  }

  @FilterableField()
  @prop({ required: true })
  title: string

  @FilterableField()
  @prop({ required: true })
  completed: boolean

  @FilterableField(() => ID)
  @prop({ ref: User })
  owner: Ref<User>
}
```

### CODE REVIEW

**Comment by marian2js** [comment]
@doug-martin I think this can be merged without aggregations since it is an optional feature. Currently anyone trying to use them would get a "non implemented" exception. I won't have time to work on the feature for the time being.
Let me know if you'd like something else to be done before merging.

**Comment by doug-martin** [comment]
@marian2js I'm going to pull this down and start looking the things

The things I see missing/need updating are
* An example with e2e tests - I found this is the best way to catch any odd serialization bugs from the nest framework
* Documentation - Add to the persistence section
* Clean up all references to typeorm. 
* I think we should change the query service return an entity instance (I could be wrong here haven't used typegoose). 
  * This will probably lead to weird assembler, luckily I had to do something similar for `sequelize` you can check out https://github.com/doug-martin/nestjs-query/blob/master/packages/query-sequelize/src/providers.ts#L14-L16 

The other thing I had questions about are the relations, I realize relations are different in a document database, since they are typically embedded, we should exaplain what is supported and not supported and reasoning why. In particular mutations, is it expected to just add/remove relations by calling update

**Comment by marian2js** [comment]
Thanks for checking out the changes. I updated the checklist in the PR description.

Regarding the relationships, in MongoDB there are normally 2 ways of referencing entities, using nested objects or referencing other documents by ID. Both alternatives are supported by the current implementation using `@Relation`.
The example in the PR shows how to use a reference by ID, using a nested one would be the same but without the ref.

I need to check if it would be possible to return entity instances. Typegoose has getter/setter decorators that I'm not sure when are resolved. I will have a look in the next days.

**Comment by marian2js** [comment]
@doug-martin I expended some time this morning trying to setup the e2e just to run the most basic thing, but I started having error after error and there is no documentation on the project around this.

Sadly I don't have the time right now to keep working on this, I started the collaboration because I wanted to try this project with mongo in something personal I was hacking, but this PR become larger than what I was expecting and because of work and other projects, I can't dedicate more time to this for the time being. Maybe in a few weeks or months and I would be able to came back and finish it.

I hope someone from the community can take this on and complete the work. If this project keeps gaining popularity is very likely someone else will want to use it with Mongo. And of course, feel free to ask any questions about my changes.

**Comment by doug-martin** [comment]
@marian2js I picked this up and am finishing up the service. I did make the change to use the official `@nestjs/mongoose` package. I also made some changes to support refs as well as virtual refs. I hope to have a release in the next week or so.

**Comment by doug-martin** [comment]
published under `v0.21.0`

**Pull request closed without merging**
