### PR TITLE
fix(bug): update update connection hasPreviousPage bug

### PR DESCRIPTION
**Pull request by zerox12311**

### CODE REVIEW

**Comment by doug-martin** [comment]
@zerox12311 thank you for the pr! Can you add a test that fails in the previous version and passes with you patch to catch future regressions?

**Comment by doug-martin** [comment]
I looked into this a little further, I based this implementation off of https://github.com/graphql/graphql-relay-js/blob/master/src/connection/arrayconnection.js#L58, which will act the same way.

I think we could update this method to the following.

```ts
private static createPageInfo(dtos: DTO[], pagingInfo: CursorPagingType): PageInfoType {
  const { length } = dtos;
  const baseOffset = pagingInfo.offset ?? 0;
  const baseLimit = pagingInfo.limit ?? 0;
  const startCursor = offsetToCursor(baseOffset);
  const endCursor = offsetToCursor(baseOffset + length - 1);
  const hasNextPage = length >= baseLimit;
  const hasPreviousPage = baseOffset > 0;
  return new PIT(hasNextPage, hasPreviousPage, startCursor, endCursor);
}
```

But I'll need to investigate more, since it breaks a couple of tests. 

Thank you for pointing this out!

**Comment by zerox12311** [comment]
Ok!
I will add some test spec catch future regressions.

**Comment by zerox12311** [comment]
I looked into this a little further.
I found some question in this case.
Maybe we need to know how many rows in database to understand it is an end of last page or some method to know the last cursor is the last row in database.
If without this info, I use the **after** and **first** and the database rows is happened to be divisible, It will return **true**, how do you think about it?

**Comment by johannesschobel** [comment]
Dear @doug-martin  and @zerox12311 ,

funny, i just noticed the same issue with the `pageInfo -> hasNextPage`. At least i think, it is the same issue.

You can easily reproduce it like this:
1) download the latest `nestjs-query` package
2) run the following commands - this will set up the "example" project properly
```bash
npm run bootstrap
cd examples/nestjs-query-typeorm
npm install
docker-compose up -d
npm run schema:sync
npm run seed
```
3) open `http://localhost:3000/graphql` in your browser
4) add the following mutation 4x:
```gql
mutation {
  createOneTodoItem(input: { todoItem: { title: "foobar", completed: false } }) {
    id
  }
}
```
5) Now query the `todo items` like this:
```gql
# Write your query or mutation here
{
  todoItems(paging:{first:4}) {
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      node {
        id
        title
      }
    }
  }
}
```
this will output, that there is another page available - which is clearly wrong. If you query the "next page" via `after: CURSOR`, it returns an empty `edges` array..

All the best,
Johannes

**Comment by doug-martin** [comment]
@johannesschobel @zerox12311 

Yep, that is a limitation of the current approach. I went with a simple limit/offset at first wrapped in a connection so it could be swapped out later on with a better implementation.

What I haven't been able to find is a performant and generic way to do this properly without doing a count, which I would like to avoid. Granted I didnt spend a whole lot of time on this implementation. 

I'll start looking into this next, but if either of you have a suggestion on how to tackle this I'd like the suggestions.

The first thing I was going to look at was increasing the limit to include 1 more record from what was passed in to determine if there is a next page, and hasPreviousPage can check offset. This still has the drawback of the data potentially changing between queries and resulting in same query returning different records.

What I would like to get to is a generic way to do the paging where the cursor doesnt represent an offset which is what the relay library does.

**Comment by doug-martin** [comment]
Closed and reopened to get the checks running properly.

**Comment by zerox12311** [comment]
> @johannesschobel @zerox12311
> 
> Yep, that is a limitation of the current approach. I went with a simple limit/offset at first wrapped in a connection so it could be swapped out later on with a better implementation.
> 
> What I haven't been able to find is a performant and generic way to do this properly without doing a count, which I would like to avoid. Granted I didnt spend a whole lot of time on this implementation.
> 
> I'll start looking into this next, but if either of you have a suggestion on how to tackle this I'd like the suggestions.
> 
> The first thing I was going to look at was increasing the limit to include 1 more record from what was passed in to determine if there is a next page, and hasPreviousPage can check offset. This still has the drawback of the data potentially changing between queries and resulting in same query returning different records.
> 
> What I would like to get to is a generic way to do the paging where the cursor doesnt represent an offset which is what the relay library does.

I think ... if we force add a createAt timestamp field in each table , we can use it to judge what data should be paging.

**Comment by johannesschobel** [comment]
Dear @doug-martin ,
first of all - thank you very much for the detailed explanation on this issue :+1: 

@zerox12311 : 
I dont see, how a `createdAt` field would help us to determine, if there are any more entries available (and hence, any more pages).

@doug-martin : 
I am not particularly fond of your idea of "fetching an additional entry" and check, if you get this entry of not. Consider, for example, a complex database-structure with a lot of relationships between entities. This would result in an additional "core entity" that you would fetch - and then multiple joins, because this entity would be connected to various other entities. This may impact the speed of the queries (and hence, the overall performance of the API) dramatically.

Why are you against the `count` query? Because TypeOrm solves it as an extra db query?

All the best

**Comment by doug-martin** [comment]
Closing in favor of #144

**Pull request closed without merging**
