### PR TITLE
feat(query-typeorm): allow filtering on nested relations

### PR DESCRIPTION
**Pull request by steinroe**
First implementation on #1041

Would love to get some feedback, especially on how to write proper tests for this.

### CODE REVIEW

**Comment by steinroe** [comment]
this will collide with #1331, but should be easy to merge

**Comment by doug-martin** [comment]
@steinroe is this ready to be moved from the draft stage? I would like to include it in the `v0.30.0` release if possible.

**Comment by steinroe** [comment]
@doug-martin not yet - I will open two new PRs hopefully by the end of the week. When do you plan to release 0.30?

**Comment by doug-martin** [comment]
I was hoping to get it out this week, it includes a lot of the outstanding dependency upgrades namely the nestjs/graphql@v9 upgrade with the updated apollo packages. If you have two more incoming PRs I will just go ahead and publish and get yours in the next release. Thanks for taking this on!

**Comment by steinroe** [comment]
Sounds good to me!

**Comment by steinroe** [comment]
closing in favour of #1354

**Pull request closed without merging**
