### PR TITLE
feat: Adds Typegoose as an alternative Mongoose/ MongoDB capable package 

### PR DESCRIPTION
**Pull request by smolinari**
Hi Doug,

This is to resolve: https://github.com/doug-martin/nestjs-query/issues/645

What this PR offers:

 - [x] Unit and e2e tested code. There are currently 5 failing tests in total. 4 from the original packages (testing with Node v14.15.1 (npm v7.1.0 and Node v12.19.0 (npm v6.14.8)) and one new one from the Typegoose package. The source of the failing Typegoose test (a type error) is within @nestjs-query/core and I'm not sure how to fix it. I did try, but with no luck. This is the error: 

image

I'm hoping you might know a quick remedy? 😊  

 - [x] Fairly complete Docs for the new Typegoose package. 

The docs are pretty much complete. 

Most of the work was done by @JohnMcInall. I personally really appreciate all the work he put into this package and I am sure others, who are interested in the Typegoose version of Mongoose, will too. 

I'd like to also suggest, I can help with any support necessary for this and the other packages, should this PR be accepted. I will help where I can and see this very much as a continuing learning experience. I can also help with any additions of features moving forward. 

Again, hope this PR is "ok". Any suggestions for improvement are greatly welcome. 

Scott

### CODE REVIEW

**Comment by doug-martin** [comment]
@smolinari I'm looking into this now. Last night I merged into a local branch, I was able to get the test passing by chasing line 14 in the providers.spec.ts to `expect(providers[0].useFactory(TestEntity)).toBeInstanceOf(TypegooseQueryService);`

Now I'm running into issues with typegoose and the unit tests with the mongo memory server. Once that's working I'll push up . Once that's working I'll do a more thorough review and come up with a check list of what's missing if anything.

Thank you for all the work you have put into this!

**Comment by smolinari** [comment]
Awesome!!! 😀 

Yes, do let me know if and where I can help. I'd love to learn anything I can from a/ the master. 😁 

Scott

**Comment by JohnMcInall** [comment]
@doug-martin @smolinari The original project that I built this for is coming back into scope, which means I should have time to finish off anything that is missing/needs fixed. Just let me know if you guys have any questions or need any help you guys need.

**Comment by doug-martin** [comment]
closing in favor of #846

**Pull request closed without merging**
